[package]

name = "alt"
version = "2.4.0"
authors = [ "Andrew De Ponte <cyphactor@gmail.com>", "Brian Miller <brimil01@gmail.com>", "Russ Cloak <russcloak@gmail.com>" ]

[dependencies]

argparse = "0.2.1"
walkdir = "2.0.1"
regex = "0.1.73"
lazy_static = "0.2"
